### ISSUE TITLE
Adding the id to the email to the webmaster

### ISSUE THREAD

**Issue by ngc213** [cliffparnitzky-archive/EfgFormFieldAutoId#4]
Hi,

I was planning to use this module to add a unique id number on the email sent to the webmaster every time someone fills up a form on my website. 

However, I don't find how to include it in the email template. 
I tried {{form::XXX}} with XXX being the name of the field but it didn't seem to work.

How would you do that ?

Thanks !

**Comment by cliffparnitzky** [comment]
Hi,

i don't know which function you are using, to send the email.
I tried the insert tag, to display the new id on the result page.

The name of my field is `autoid` and the value will be displayed with `{{form::autoid}}`.
So, i have no problems to do that.

Is the rest okay? Is there a new id for each submitted form?

**Comment by cliffparnitzky** [comment]
No answer. Sorry. Maybe no problem.
