### ISSUE TITLE
Update to Contao 4.9

### ISSUE THREAD

**Issue by sfx12** [cliffparnitzky-archive/EfgFormFieldAutoId#5]
Hallo,

besteht eine Möglichkeit das in Contao 4.9x upzudaten !?

Das wäre Mega!

**Comment by cliffparnitzky** [comment]
Moin,
nein, diese Erweiterung wird nicht mehr forgeführt.

Es handlet sich hierbei um ein Erweiterung für die EFG Extension, die nicht mehr für Contao 4 existiert.
